### ISSUE TITLE
Enkoting of array leads to incorrect result

### ISSUE THREAD

**Issue by letko-dmitry** [artemstepanenko/Dekoter#12]
Hi,

It seems there is misprint in the realization of the `public func enkotObject(_ object: [Koting]?, forKey key: AnyHashable)`. `flatMap` is used there and it leads to unwrapping of `Data` as an array of `UInt8`. As a result we get a massive collection of `UInt8`.
While dekoting we cast the collection to array of `Data` type and the cast always fails. Please, check the `public func dekotObject<T: Koting>(forKey key: AnyHashable) -> [T]?`.
I think simple use `map` instead of `flatMap` will make the mechanism behave as expected.

**Comment by artemstepanenko** [comment]
Hello, @letko-dmitry .
Thank you so much for creating such a well-explained issue and making a PR.
Your PR is merged. No doubts the unwrapping was useless.
Also, I want to investigate the problem a bit more, I never thought of anything like this.

**Comment by letko-dmitry** [comment]
Thanks.
