### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by letko-dmitry** [artemstepanenko/Dekoter#14]
Hi,
Could you release new version of the library? At least it'll fix the issue (#12) with collections and help to keep `podfile` where it is mentioned clean. Not sure if I can do it by myself.
Thanks a lot in advance.

**Comment by artemstepanenko** [comment]
Hello, @letko-dmitry . I've posted a new version [0.2.2](https://github.com/artemstepanenko/Dekoter/releases/tag/0.2.2) with a change you made to cocoapods. Is it what you wanted?

**Comment by letko-dmitry** [comment]
Yes. Thanks a lot.
