### ISSUE TITLE
CocoaPods installing an old version

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [artemstepanenko/Dekoter#18]
Hi,

I installed the library via CocoaPods like so `pod 'Dekoter'`. But it installed an older version (0.2.2). 

I had to manually point to the repo like this `pod 'Dekoter', :git => 'https://github.com/artemstepanenko/Dekoter.git'` to get the latest 0.3.0 version.

**Comment by artemstepanenko** [comment]
Hello, @Isuru-Nanayakkara . This is strange. I checked [the cocoapods portal](https://cocoapods.org/?q=dekoter) and the podspec, everything looks fine. Could it be because the old version was captured in the lockfile? If so, maybe, `pod update` can help? Thanks for the issue.

**Comment by Isuru-Nanayakkara** [comment]
Okay, I ran `pod repo update` prior to running `pod install` and it installed the latest version. My bad. Thanks for the prompt reply.
