### ISSUE TITLE
Enkoting an array of structs causes a crash

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [artemstepanenko/Dekoter#22]
Hi,

I have two simple structs like this.

```swift
import Foundation
import Dekoter

struct Shop {
    let id: Int
    let employees: [String]
    let fruits: [Fruit]
}

extension Shop: Koting {
    private struct Key {
        static let id = "Id"
        static let employees = "Employees"
        static let fruits = "Fruits"
    }
    
    public init?(koter: Koter) {
        guard let id: Int = koter.dekotObject(forKey: Key.id) else { return nil }
        guard let employees: [String] = koter.dekotObject(forKey: Key.employees) else { return nil }
        guard let fruits: [Fruit] = koter.dekotObject(forKey: Key.fruits) else { return nil }
        
        self.init(id: id, employees: employees, fruits: fruits)
    }
    
    public func enkot(with koter: Koter) {
        koter.enkotObject(id, forKey: Key.id)
        koter.enkotObject(employees, forKey: Key.employees)
        koter.enkotObject(fruits, forKey: Key.fruits)
    }
}

import Foundation
import Dekoter

struct Fruit {
    let id: Int
    let name: String
}

extension Fruit: Koting {
    private struct Key {
        static let id = "Id"
        static let name = "Name"
    }
    
    public init?(koter: Koter) {
        guard let id: Int = koter.dekotObject(forKey: Key.id) else { return nil }
        guard let name: String = koter.dekotObject(forKey: Key.name) else { return nil }
        
        self.init(id: id, name: name)
    }
    
    public func enkot(with koter: Koter) {
        koter.enkotObject(id, forKey: Key.id)
        koter.enkotObject(name, forKey: Key.name)
    }
}
```

I save one `Shop` object with 3 employees and 2 `Fruit` objects.

```swift
let fruit1 = Fruit(id: 1, name: "Apple")
let fruit2 = Fruit(id: 2, name: "Orange")
let shop = Shop(id: 1, employees: ["Max", "Susan", "John"], fruits: [fruit1, fruit2])
        
UserDefaults.standard.de_set(shop, forKey: "MyShop")
let myShop: Shop? = UserDefaults.standard.de_object(forKey: "MyShop")
print(myShop)
```

But when I try to save the `shop` object, it crashes with the following error.

> -[_SwiftValue encodeWithCoder:]: unrecognized selector sent to instance 0x14688be0
> 2017-11-18 14:13:46.676966+0530 DekoteDemo[4171:1181357] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[_SwiftValue encodeWithCoder:]: unrecognized selector sent to instance 0x14688be0'

It seems that the error is due to the `let fruits: [Fruit]` property in the `Shop` object. I can save the `employees` property which is a string array with no problem. But the `fruits` array causing the crash.

Not sure why it's happening. The `Fruit` object is also conforming to the `Koting` protocol. I uploaded a demo project [here](https://www.dropbox.com/s/asxj78wuin08t83/DekoteDemo.zip?dl=0).

**Comment by artemstepanenko** [comment]
Hello @Isuru-Nanayakkara . I'll try to fix it on the weekend. Is it fine with you?

**Comment by Isuru-Nanayakkara** [comment]
Sure @artemstepanenko. Thanks for the response.

**Comment by Isuru-Nanayakkara** [comment]
Hi @artemstepanenko, were you able to fix this?

**Comment by artemstepanenko** [comment]
Hello @Isuru-Nanayakkara! I'm so sorry, I didn't have time for the issue so far. I'll try to fix it in the next days. I hope it's fine with you. Or would you consider fixing it yourself and creating a pull request?

**Comment by Isuru-Nanayakkara** [comment]
Hello again, @artemstepanenko. Sorry about the delay. I was caught up with some of my own work so didn't have time to look into this properly until today.

I think I managed to find the issue!

I noticed that this crash only occurred if a struct has an array of another struct (both conforming to `Koting`). It worked fine if a struct has say, an array of strings.

As you know, there are three overloads for the `enkotObject` method.

```swift
func enkotObject(_ object: Koting?, forKey key: AnyHashable)
func enkotObject(_ object: [Koting]?, forKey key: AnyHashable)
func enkotObject(_ object: Any?, forKey key: AnyHashable)
```

Let's take a struct like this for example.

```swift
struct Basket {
    let id: Int
    let fruits: [Fruit]  // Fruit is also a struct conforming to `Koting`
}
```

When you enkote the fruits array like so `koter.enkotObjects(fruits, forKey: Key.fruits)`, the Swift runtime picks the third overload, `func enkotObject(_ object: Any?, forKey key: AnyHashable)` instead of the `func enkotObject(_ object: [Koting]?, forKey key: AnyHashable)` overload which seemed to be causing the crash.

What I did was simply renamed the `func enkotObject(_ object: [Koting]?, ...` to `func enkotObjects(_ object: [Koting]?, ...` and tried it and it worked!

Please check this [demo project](https://www.dropbox.com/s/5mrjemd9qnu77m9/DekoterFix.zip?dl=0) I put together to test each case.

I didn't create a PR because I'm not sure how you want to proceed with this information. Whether to rename the function or fix it some other way. Anyway, hope this helps you to quickly patch this up.

**Comment by artemstepanenko** [comment]
Hello @Isuru-Nanayakkara . Thanks for details, I'll check it.

**Comment by artemstepanenko** [comment]
@Isuru-Nanayakkara I'm so sorry but looks like I don't have time to maintain this library. I don't know when and if it changes.

**Comment by artemstepanenko** [comment]
@Isuru-Nanayakkara if create a fork and then a PR, I can merge it to the repo.

**Comment by artemstepanenko** [comment]
@Isuru-Nanayakkara is this issue still actual? (I just think the whole library is ultimately useless after Swift 4 was released.)

**Comment by Isuru-Nanayakkara** [comment]
Yes. I'm working with a [PR](https://github.com/Isuru-Nanayakkara/Dekoter) in which I added a workaround described above. I wasn't sure if that's the ideal way to do it so that's why I didn't submit it.

Regarding your last comment, why do you say so? Can you archive structs in Swift 4?

**Comment by artemstepanenko** [comment]
Yes! Check out [this article](https://hackernoon.com/everything-about-codable-in-swift-4-97d0e18a2999) or any other about `Codable`.

**Comment by Isuru-Nanayakkara** [comment]
Oh that's awesome! I did not know this. Thanks.

**Comment by artemstepanenko** [comment]
@Isuru-Nanayakkara this is how the library lost its single user.

**Comment by Isuru-Nanayakkara** [comment]
Haha it was a good run 😋 But I have two projects using this library. I won't be redoing saving structs in pure Swift right away so..
